-- Production-safe starter tour packages. Run after seed.sql (needs its destinations).
-- Every tour is QUOTE_ONLY: no prices are published, the owner quotes each request.
-- Routes are classic, widely-run Sri Lanka itineraries; adjust or unpublish them in
-- Admin → Tours. Idempotent: existing slugs are left untouched.

insert into public.tours (slug, name, short_description, description, categories, duration_days, duration_nights,
  traveler_types, vehicle_options, max_group_size, price_mode, inclusions, exclusions, add_ons,
  cover_image_url, cover_image_alt, image_credit, seo_title, seo_description, is_featured, status, sort_order)
values
('cultural-triangle-and-hill-country', 'Cultural Triangle & Hill Country',
 'Rock fortresses, cave temples, Kandy and the tea hills at an unhurried pace.',
 'A classic first journey through Sri Lanka''s ancient cities and cool tea country, with a private driver throughout. Climb Sigiriya at sunrise, explore the Dambulla cave temples, spend an evening in Kandy and ride the hill-country train to Ella. Every day can be adjusted to your interests and pace.',
 array['cultural', 'hill-country', 'scenic-train', 'round-tour'], 7, 6,
 array['Couples', 'Families', 'First-time visitors'], array['Car', 'SUV', 'Van'], 12, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with English-speaking driver', 'Fuel, parking and highway tolls', 'Airport pickup and drop-off', 'Driver''s meals and accommodation'],
 array['International flights', 'Accommodation unless arranged in your quotation', 'Entrance tickets', 'Meals', 'Personal expenses and tips'],
 '[{"name":"Reserved train seats","description":"Kandy or Nanu Oya to Ella, subject to availability"},{"name":"Jeep safari at Minneriya or Kaudulla","description":"Elephant gathering, roughly July to October"}]'::jsonb,
 'https://images.unsplash.com/photo-1612862862126-865765df2ded', 'Aerial view of the Sigiriya rock fortress rising above dense green forest', 'Photo: Dylan Shaw / Unsplash',
 'Cultural Triangle & Hill Country 7-day private tour', 'A 7-day private Sri Lanka tour through Sigiriya, Dambulla, Kandy, Nuwara Eliya and Ella with your own driver.',
 true, 'published', 1),

('classic-sri-lanka-10-days', 'Classic Sri Lanka in 10 Days',
 'The island''s highlights in one loop: ancient cities, tea country, a leopard safari and the south coast.',
 'The most popular way to see Sri Lanka on a first visit. Start in the Cultural Triangle, head up into the hills by road and rail, drop down to Yala for a safari, then finish with Galle Fort and the beaches of the south coast before returning to the airport.',
 array['round-tour', 'cultural', 'hill-country', 'wildlife', 'beach', 'scenic-train'], 10, 9,
 array['Couples', 'Families', 'First-time visitors', 'Friends'], array['Car', 'SUV', 'Van'], 12, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with English-speaking driver', 'Fuel, parking and highway tolls', 'Airport pickup and drop-off', 'Driver''s meals and accommodation'],
 array['International flights', 'Accommodation unless arranged in your quotation', 'Entrance tickets and safari jeep', 'Meals', 'Personal expenses and tips'],
 '[{"name":"Reserved train seats","description":"Hill-country train, subject to availability"},{"name":"Yala safari jeep","description":"Half-day or full-day, with park fees"},{"name":"Whale watching from Mirissa","description":"Roughly November to April"}]'::jsonb,
 'https://images.unsplash.com/photo-1578519050142-afb511e518de', 'A train crossing a bridge through the forest near Ella', 'Photo: Anton Lecock / Unsplash',
 'Classic Sri Lanka 10-day private round tour', 'Ten days with your own driver: Sigiriya, Kandy, Ella, Yala, Galle and the south coast beaches. Tailored to you.',
 true, 'published', 2),

('grand-tour-of-sri-lanka-14-days', 'Grand Tour of Sri Lanka',
 'Two unhurried weeks: ancient capitals, tea country, safari, whales and beach time.',
 'For travellers who want to see the island properly without rushing. This route adds the ancient capital of Polonnaruwa, a night in the tea estates, an extra safari day and several slow days on the south and west coasts.',
 array['round-tour', 'cultural', 'hill-country', 'wildlife', 'beach', 'scenic-train'], 14, 13,
 array['Couples', 'Families', 'Slow travellers'], array['Car', 'SUV', 'Van'], 12, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with English-speaking driver', 'Fuel, parking and highway tolls', 'Airport pickup and drop-off', 'Driver''s meals and accommodation'],
 array['International flights', 'Accommodation unless arranged in your quotation', 'Entrance tickets and safari jeeps', 'Meals', 'Personal expenses and tips'],
 '[{"name":"Reserved train seats","description":"Hill-country train, subject to availability"},{"name":"Tea factory visit with tasting","description":"Nuwara Eliya or Ella"},{"name":"Whale watching from Mirissa","description":"Roughly November to April"}]'::jsonb,
 'https://images.unsplash.com/photo-1568843240915-b512cc9b4415', 'The white lighthouse at Galle Fort', 'Photo: Shainee Fernando / Unsplash',
 'Grand Tour of Sri Lanka: 14-day private tour', 'Two weeks around Sri Lanka with a private driver: Anuradhapura region, Kandy, Ella, Yala, Galle and the beaches.',
 false, 'published', 3),

('south-coast-beaches-and-yala', 'South Coast Beaches & Yala',
 'Galle Fort, palm-lined bays and a leopard safari in Yala.',
 'Slow days on the south coast combined with an early-morning safari in Yala National Park, home to one of the highest densities of leopards in the world. Best from November to April, when the south coast seas are calm.',
 array['beach', 'wildlife'], 6, 5,
 array['Couples', 'Honeymooners', 'Families'], array['Car', 'SUV'], 8, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with driver', 'Fuel, parking and highway tolls', 'Airport pickup and drop-off'],
 array['Safari jeep and park fees', 'Accommodation unless arranged in your quotation', 'Meals', 'Personal expenses and tips'],
 '[{"name":"Yala safari jeep","description":"Morning or full-day, with park fees"},{"name":"Whale watching from Mirissa","description":"Roughly November to April"}]'::jsonb,
 'https://images.unsplash.com/photo-1580910527739-556eb89f9d65', 'Palm trees along the beach shore at Mirissa', 'Photo: Dinuka Lankaloka / Unsplash',
 'South coast beaches & Yala safari private tour', 'Six days between Galle, Mirissa and Yala with a private driver, planned around you.',
 true, 'published', 4),

('sri-lanka-wildlife-safari', 'Sri Lanka Wildlife Safari',
 'Elephants at Minneriya, Udawalawe''s herds and leopards in Yala.',
 'A wildlife-focused journey through three of Sri Lanka''s best national parks. Watch elephants gather at the Minneriya reservoir, see young elephants at the Udawalawe transit home and search for leopard and sloth bear in Yala. Safari timings are planned around park seasons.',
 array['wildlife', 'adventure'], 6, 5,
 array['Wildlife lovers', 'Families', 'Photographers'], array['Car', 'SUV', 'Van'], 10, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with English-speaking driver', 'Fuel, parking and highway tolls', 'Airport pickup and drop-off', 'Driver''s meals and accommodation'],
 array['Safari jeeps and park fees', 'Accommodation unless arranged in your quotation', 'Meals', 'Personal expenses and tips'],
 '[{"name":"Safari jeeps with park fees","description":"Minneriya or Kaudulla, Udawalawe and Yala"},{"name":"Full-day Yala safari","description":"Packed breakfast and lunch"}]'::jsonb,
 'https://images.unsplash.com/photo-1621847473222-d85c022cbf07', 'A leopard standing in water in Yala National Park', 'Photo: Udara Karunarathna / Unsplash',
 'Sri Lanka wildlife safari tour: Minneriya, Udawalawe, Yala', 'Six-day private wildlife tour with your own driver: elephants at Minneriya and Udawalawe, leopards in Yala.',
 false, 'published', 5),

('sri-lanka-honeymoon', 'Sri Lanka Honeymoon',
 'Misty tea country, the scenic train and slow beach days for two.',
 'A relaxed route for couples: a few cool days in the hills with tea estates and waterfalls, the famous train ride to Ella, then time to unwind on the south coast. We suggest boutique stays and leave plenty of free time.',
 array['honeymoon', 'hill-country', 'beach', 'scenic-train'], 8, 7,
 array['Honeymooners', 'Couples'], array['Car', 'SUV'], 2, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with English-speaking driver', 'Fuel, parking and highway tolls', 'Airport pickup and drop-off', 'Driver''s meals and accommodation'],
 array['International flights', 'Accommodation unless arranged in your quotation', 'Entrance tickets', 'Meals', 'Personal expenses and tips'],
 '[{"name":"Reserved train seats","description":"Subject to availability"},{"name":"Sunset catamaran or whale watching","description":"South coast, seasonal"}]'::jsonb,
 'https://images.unsplash.com/photo-1708338914870-797de586672d', 'A lush green hillside covered in trees in the Nuwara Eliya region', 'Photo: Juho S / Unsplash',
 'Sri Lanka honeymoon: 8-day private tour for couples', 'Eight days for two: Kandy, tea country, the Ella train and south coast beaches, with your own driver.',
 true, 'published', 6),

('east-coast-summer-escape', 'East Coast Summer Escape',
 'Trincomalee''s calm summer seas and the surf town of Arugam Bay.',
 'When the south and west coasts are windy (roughly May to September), the east coast is at its best. Combine Sigiriya with Trincomalee''s beaches, snorkelling at Pigeon Island and a few days in laid-back Arugam Bay.',
 array['beach', 'adventure', 'cultural'], 7, 6,
 array['Couples', 'Friends', 'Surfers'], array['Car', 'SUV', 'Van'], 10, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with English-speaking driver', 'Fuel, parking and highway tolls', 'Airport pickup and drop-off', 'Driver''s meals and accommodation'],
 array['Accommodation unless arranged in your quotation', 'Boat trips and snorkelling', 'Entrance tickets', 'Meals', 'Personal expenses and tips'],
 '[{"name":"Pigeon Island snorkelling trip","description":"Boat and park fees"},{"name":"Surf lessons at Arugam Bay","description":"Beginner-friendly breaks nearby"}]'::jsonb,
 'https://images.unsplash.com/photo-1552055568-f8c4fb8c6320', 'Aerial view of fishing boats on the shore at Arugam Bay', 'Photo: Tomáš Malík / Unsplash',
 'East coast Sri Lanka tour: Trincomalee & Arugam Bay', 'A 7-day private summer tour of Sri Lanka''s east coast: Sigiriya, Trincomalee and Arugam Bay.',
 false, 'published', 7),

('kandy-and-tea-country-short-break', 'Kandy & Tea Country Short Break',
 'Three days in Kandy and the cool hills of Nuwara Eliya.',
 'A short escape from Colombo or the beach. Visit the Temple of the Tooth and the Peradeniya botanic gardens, then climb into tea country for a factory visit and cool evenings in Nuwara Eliya.',
 array['cultural', 'hill-country', 'family'], 3, 2,
 array['Couples', 'Families', 'Short stays'], array['Car', 'SUV', 'Van'], 12, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with English-speaking driver', 'Fuel, parking and highway tolls', 'Pickup and drop-off in Colombo, Negombo or the airport', 'Driver''s meals and accommodation'],
 array['Accommodation unless arranged in your quotation', 'Entrance tickets', 'Meals', 'Personal expenses and tips'],
 '[]'::jsonb,
 'https://images.unsplash.com/photo-1665849050332-8d5d7e59afb6', 'A white building with a gold roof beside the Temple of the Tooth in Kandy', 'Photo: Chathura Anuradha Subasinghe / Unsplash',
 'Kandy & Nuwara Eliya 3-day private tour', 'A 3-day private trip from Colombo to Kandy and the Nuwara Eliya tea country with your own driver.',
 false, 'published', 8),

('kandy-to-ella-train-with-luggage-transfer', 'Kandy to Ella by Train',
 'Ride the famous hill-country railway while your driver carries your luggage by road.',
 'One of the world''s most scenic train journeys, through tea estates and misty hills. We drop you at the station, take your luggage by road and meet you at Ella.',
 array['scenic-train', 'day-trip', 'hill-country'], 1, 0,
 array['Solo travellers', 'Couples', 'Friends'], array['Car', 'Van'], 6, 'QUOTE_ONLY',
 array['Drop-off at Kandy, Peradeniya or Nanu Oya station', 'Luggage transfer and pickup at Ella'],
 array['Train tickets unless added to your quotation', 'Meals'],
 '[{"name":"Reserved train seats","description":"Subject to availability"}]'::jsonb,
 'https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9', 'A blue train crossing the Nine Arches Bridge in Ella', 'Photo: Hendrik Cornelissen / Unsplash',
 'Kandy to Ella scenic train with luggage transfer', 'Take the Kandy–Ella train while your driver transfers your luggage and meets you at the station.',
 false, 'published', 9),

('galle-day-trip-from-colombo', 'Galle & South Coast Day Trip',
 'Galle Fort, stilt fishermen and a beach stop, returning the same evening.',
 'A full day down the Southern Expressway from Colombo or Negombo. Walk the ramparts of the Dutch-era Galle Fort, see the stilt fishermen near Koggala and stop at a turtle hatchery or a quiet beach on the way back.',
 array['day-trip', 'cultural', 'beach'], 1, 0,
 array['Families', 'Couples', 'Short stays'], array['Car', 'SUV', 'Van'], 12, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with driver', 'Fuel, parking and highway tolls', 'Hotel pickup and drop-off'],
 array['Entrance tickets', 'Meals', 'Tips'],
 '[]'::jsonb,
 'https://images.unsplash.com/photo-1519566335946-e6f65f0f4fdf', 'Stilt fishermen on wooden poles in the shallow coastal waters of Sri Lanka', 'Photo: Daniel Klein / Unsplash',
 'Galle day trip from Colombo with private driver', 'A private day trip from Colombo or Negombo to Galle Fort and the south coast, back the same evening.',
 false, 'published', 10),

('sigiriya-and-dambulla-day-trip', 'Sigiriya & Dambulla Day Trip',
 'Climb the Lion Rock and visit the Golden Cave Temple in one long day.',
 'An early start from Colombo, Negombo or Kandy to reach Sigiriya before the heat. Climb the rock fortress, visit the Dambulla cave temples and add a village or jeep safari if time allows.',
 array['day-trip', 'cultural'], 1, 0,
 array['Couples', 'Families', 'Short stays'], array['Car', 'SUV', 'Van'], 12, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with driver', 'Fuel, parking and highway tolls', 'Hotel pickup and drop-off'],
 array['Entrance tickets', 'Meals', 'Tips'],
 '[{"name":"Minneriya jeep safari","description":"Afternoon, seasonal"}]'::jsonb,
 'https://images.unsplash.com/photo-1656497107500-a2bc32cbe7d4', 'A large statue in front of the temple building at Dambulla', 'Photo: Secret Travel Guide / Unsplash',
 'Sigiriya & Dambulla day trip with private driver', 'A private day trip to Sigiriya Rock and the Dambulla cave temples from Colombo, Negombo or Kandy.',
 false, 'published', 11),

('colombo-city-tour', 'Colombo City Tour',
 'Temples, colonial streets, markets and the seafront in a half or full day.',
 'See Sri Lanka''s capital with a driver who knows it: Gangaramaya Temple, Pettah market, the old Fort district, Independence Square and sunset at Galle Face Green. Ideal on arrival or before a late flight.',
 array['day-trip', 'cultural', 'family'], 1, 0,
 array['Families', 'Short stays', 'Business travellers'], array['Car', 'SUV', 'Van'], 12, 'QUOTE_ONLY',
 array['Private air-conditioned vehicle with driver', 'Fuel and parking', 'Hotel pickup and drop-off'],
 array['Entrance tickets', 'Meals', 'Tips'],
 '[]'::jsonb,
 'https://images.unsplash.com/photo-1623595289196-007a22dd8560', 'A train on tracks leading toward the Lotus Tower in Colombo at golden hour', 'Photo: Tharoushan Kandarajah / Unsplash',
 'Colombo city tour with private driver', 'A private half-day or full-day Colombo city tour: temples, Pettah market, Fort and Galle Face Green.',
 false, 'published', 12)
on conflict (slug) do nothing;

insert into public.tour_destinations (tour_id, destination_id, position)
select t.id, d.id, x.pos from (values
  ('cultural-triangle-and-hill-country', 'sigiriya', 1), ('cultural-triangle-and-hill-country', 'dambulla', 2),
  ('cultural-triangle-and-hill-country', 'kandy', 3), ('cultural-triangle-and-hill-country', 'nuwara-eliya', 4),
  ('cultural-triangle-and-hill-country', 'ella', 5),
  ('classic-sri-lanka-10-days', 'sigiriya', 1), ('classic-sri-lanka-10-days', 'dambulla', 2),
  ('classic-sri-lanka-10-days', 'kandy', 3), ('classic-sri-lanka-10-days', 'nuwara-eliya', 4),
  ('classic-sri-lanka-10-days', 'ella', 5), ('classic-sri-lanka-10-days', 'yala', 6),
  ('classic-sri-lanka-10-days', 'mirissa', 7), ('classic-sri-lanka-10-days', 'galle', 8),
  ('grand-tour-of-sri-lanka-14-days', 'sigiriya', 1), ('grand-tour-of-sri-lanka-14-days', 'dambulla', 2),
  ('grand-tour-of-sri-lanka-14-days', 'kandy', 3), ('grand-tour-of-sri-lanka-14-days', 'nuwara-eliya', 4),
  ('grand-tour-of-sri-lanka-14-days', 'ella', 5), ('grand-tour-of-sri-lanka-14-days', 'yala', 6),
  ('grand-tour-of-sri-lanka-14-days', 'mirissa', 7), ('grand-tour-of-sri-lanka-14-days', 'galle', 8),
  ('grand-tour-of-sri-lanka-14-days', 'bentota', 9), ('grand-tour-of-sri-lanka-14-days', 'colombo', 10),
  ('south-coast-beaches-and-yala', 'galle', 1), ('south-coast-beaches-and-yala', 'mirissa', 2),
  ('south-coast-beaches-and-yala', 'yala', 3),
  ('sri-lanka-wildlife-safari', 'sigiriya', 1), ('sri-lanka-wildlife-safari', 'yala', 2),
  ('sri-lanka-honeymoon', 'kandy', 1), ('sri-lanka-honeymoon', 'nuwara-eliya', 2),
  ('sri-lanka-honeymoon', 'ella', 3), ('sri-lanka-honeymoon', 'mirissa', 4), ('sri-lanka-honeymoon', 'galle', 5),
  ('east-coast-summer-escape', 'sigiriya', 1), ('east-coast-summer-escape', 'trincomalee', 2),
  ('east-coast-summer-escape', 'arugam-bay', 3),
  ('kandy-and-tea-country-short-break', 'kandy', 1), ('kandy-and-tea-country-short-break', 'nuwara-eliya', 2),
  ('kandy-to-ella-train-with-luggage-transfer', 'kandy', 1), ('kandy-to-ella-train-with-luggage-transfer', 'ella', 2),
  ('galle-day-trip-from-colombo', 'galle', 1),
  ('sigiriya-and-dambulla-day-trip', 'sigiriya', 1), ('sigiriya-and-dambulla-day-trip', 'dambulla', 2),
  ('colombo-city-tour', 'colombo', 1)
) as x(tour_slug, dest_slug, pos)
join public.tours t on t.slug = x.tour_slug
join public.destinations d on d.slug = x.dest_slug
on conflict do nothing;

insert into public.tour_itinerary_days (tour_id, day_number, title, description, overnight)
select t.id, x.day, x.title, x.descr, x.overnight from (values
  ('cultural-triangle-and-hill-country', 1, 'Arrival and drive to Sigiriya', 'Meet your driver at the airport and travel north to the Cultural Triangle.', 'Sigiriya'),
  ('cultural-triangle-and-hill-country', 2, 'Sigiriya and Pidurangala', 'An early climb of the rock fortress, with the afternoon free, a village visit or a jeep safari.', 'Sigiriya'),
  ('cultural-triangle-and-hill-country', 3, 'Dambulla to Kandy', 'Visit the Dambulla cave temples and a spice garden, then continue to Kandy.', 'Kandy'),
  ('cultural-triangle-and-hill-country', 4, 'Kandy', 'The Temple of the Tooth, the Peradeniya botanic gardens and an evening cultural show.', 'Kandy'),
  ('cultural-triangle-and-hill-country', 5, 'Into tea country', 'Drive up through waterfalls and tea estates to Nuwara Eliya, with a tea factory visit.', 'Nuwara Eliya'),
  ('cultural-triangle-and-hill-country', 6, 'The train to Ella', 'Ride the hill-country train while your driver meets you in Ella. Evening at Nine Arches Bridge.', 'Ella'),
  ('cultural-triangle-and-hill-country', 7, 'Little Adam''s Peak and departure', 'A short sunrise hike, then the drive back to the airport or on to the coast.', null),

  ('classic-sri-lanka-10-days', 1, 'Arrival and drive to Sigiriya', 'Meet your driver at the airport and head north to the Cultural Triangle.', 'Sigiriya'),
  ('classic-sri-lanka-10-days', 2, 'Sigiriya Rock', 'Climb the rock fortress early, then an optional village tour or elephant safari.', 'Sigiriya'),
  ('classic-sri-lanka-10-days', 3, 'Dambulla to Kandy', 'The Dambulla cave temples and a spice garden on the way to Kandy.', 'Kandy'),
  ('classic-sri-lanka-10-days', 4, 'Kandy', 'Temple of the Tooth, the botanic gardens and the lake.', 'Kandy'),
  ('classic-sri-lanka-10-days', 5, 'Tea country', 'Drive into the hills past waterfalls, with a tea factory visit.', 'Nuwara Eliya'),
  ('classic-sri-lanka-10-days', 6, 'Train to Ella', 'The famous train ride, then an evening at Nine Arches Bridge.', 'Ella'),
  ('classic-sri-lanka-10-days', 7, 'Ella to Yala', 'Morning hike to Little Adam''s Peak, then down to the plains near Yala.', 'Tissamaharama'),
  ('classic-sri-lanka-10-days', 8, 'Yala safari and the coast', 'An early safari in search of leopards, then on to the south coast.', 'Mirissa'),
  ('classic-sri-lanka-10-days', 9, 'Galle Fort', 'Beach time, optional whale watching and an afternoon in Galle Fort.', 'Mirissa'),
  ('classic-sri-lanka-10-days', 10, 'Departure', 'Drive to the airport via the Southern Expressway.', null),

  ('grand-tour-of-sri-lanka-14-days', 1, 'Arrival', 'Meet your driver and rest near the airport or in Negombo.', 'Negombo'),
  ('grand-tour-of-sri-lanka-14-days', 2, 'To the Cultural Triangle', 'Drive north to Sigiriya, settling in for the evening.', 'Sigiriya'),
  ('grand-tour-of-sri-lanka-14-days', 3, 'Polonnaruwa', 'Cycle or drive around the ruins of the medieval capital, with an evening safari option.', 'Sigiriya'),
  ('grand-tour-of-sri-lanka-14-days', 4, 'Sigiriya Rock', 'An early climb of the rock fortress and a relaxed afternoon.', 'Sigiriya'),
  ('grand-tour-of-sri-lanka-14-days', 5, 'Dambulla to Kandy', 'Cave temples and a spice garden on the way to Kandy.', 'Kandy'),
  ('grand-tour-of-sri-lanka-14-days', 6, 'Kandy', 'Temple of the Tooth, the botanic gardens and a cultural show.', 'Kandy'),
  ('grand-tour-of-sri-lanka-14-days', 7, 'Tea country', 'Into the hills for a night on or near a tea estate.', 'Nuwara Eliya'),
  ('grand-tour-of-sri-lanka-14-days', 8, 'Horton Plains or a slow morning', 'Optional early walk to World''s End, then the afternoon train to Ella.', 'Ella'),
  ('grand-tour-of-sri-lanka-14-days', 9, 'Ella', 'A full day for hikes, waterfalls and cafés.', 'Ella'),
  ('grand-tour-of-sri-lanka-14-days', 10, 'Yala', 'Down to the plains for an afternoon safari.', 'Tissamaharama'),
  ('grand-tour-of-sri-lanka-14-days', 11, 'To the south coast', 'Morning safari option, then the coast road west.', 'Mirissa'),
  ('grand-tour-of-sri-lanka-14-days', 12, 'Mirissa and Galle', 'Beach time, optional whale watching and Galle Fort.', 'Galle'),
  ('grand-tour-of-sri-lanka-14-days', 13, 'Bentota', 'A slow day on the west coast with a river safari option.', 'Bentota'),
  ('grand-tour-of-sri-lanka-14-days', 14, 'Colombo and departure', 'A short Colombo city drive if time allows, then the airport.', null),

  ('south-coast-beaches-and-yala', 1, 'Arrival and drive to Galle', 'Meet your driver and take the expressway to the south coast.', 'Galle'),
  ('south-coast-beaches-and-yala', 2, 'Galle Fort', 'Walk the ramparts, lanes and lighthouse of the old fort.', 'Galle'),
  ('south-coast-beaches-and-yala', 3, 'To Mirissa', 'Stilt fishermen and quiet bays on the way to Mirissa.', 'Mirissa'),
  ('south-coast-beaches-and-yala', 4, 'Mirissa', 'Optional whale watching, then a free beach day.', 'Mirissa'),
  ('south-coast-beaches-and-yala', 5, 'Yala safari', 'Drive east for an afternoon safari in Yala National Park.', 'Tissamaharama'),
  ('south-coast-beaches-and-yala', 6, 'Departure', 'An optional morning safari, then the drive to the airport.', null),

  ('sri-lanka-wildlife-safari', 1, 'Arrival and drive north', 'Meet your driver and travel to the Habarana area.', 'Habarana'),
  ('sri-lanka-wildlife-safari', 2, 'Minneriya or Kaudulla', 'An afternoon jeep safari to see elephants gathering at the reservoir.', 'Habarana'),
  ('sri-lanka-wildlife-safari', 3, 'To Udawalawe', 'A long scenic drive south to Udawalawe.', 'Udawalawe'),
  ('sri-lanka-wildlife-safari', 4, 'Udawalawe', 'Morning safari among large elephant herds and a visit to the elephant transit home.', 'Tissamaharama'),
  ('sri-lanka-wildlife-safari', 5, 'Yala', 'A full day in Yala in search of leopard, sloth bear and birdlife.', 'Tissamaharama'),
  ('sri-lanka-wildlife-safari', 6, 'Departure', 'Drive to the airport or continue to the south coast.', null),

  ('sri-lanka-honeymoon', 1, 'Arrival and Kandy', 'Meet your driver and travel to a hillside stay near Kandy.', 'Kandy'),
  ('sri-lanka-honeymoon', 2, 'Kandy', 'The Temple of the Tooth, the botanic gardens and a slow evening.', 'Kandy'),
  ('sri-lanka-honeymoon', 3, 'Tea country', 'Waterfalls and a tea estate stay in the cool hills.', 'Nuwara Eliya'),
  ('sri-lanka-honeymoon', 4, 'Train to Ella', 'The scenic train ride, with your luggage going by road.', 'Ella'),
  ('sri-lanka-honeymoon', 5, 'Ella to the coast', 'Sunrise at Little Adam''s Peak, then down to the south coast.', 'Mirissa'),
  ('sri-lanka-honeymoon', 6, 'Beach day', 'Free time, with optional whale watching or a sunset cruise.', 'Mirissa'),
  ('sri-lanka-honeymoon', 7, 'Galle Fort', 'An afternoon and dinner inside the old fort.', 'Galle'),
  ('sri-lanka-honeymoon', 8, 'Departure', 'Drive to the airport via the expressway.', null),

  ('east-coast-summer-escape', 1, 'Arrival and drive to Sigiriya', 'Meet your driver and travel to the Cultural Triangle.', 'Sigiriya'),
  ('east-coast-summer-escape', 2, 'Sigiriya and on to Trincomalee', 'Climb the rock early, then continue to the east coast.', 'Trincomalee'),
  ('east-coast-summer-escape', 3, 'Trincomalee', 'Pigeon Island snorkelling and Koneswaram Temple.', 'Trincomalee'),
  ('east-coast-summer-escape', 4, 'Down the east coast', 'A long coastal drive south to Arugam Bay.', 'Arugam Bay'),
  ('east-coast-summer-escape', 5, 'Arugam Bay', 'Surf, lagoon safari or simply the beach.', 'Arugam Bay'),
  ('east-coast-summer-escape', 6, 'Arugam Bay', 'Another free day on the coast.', 'Arugam Bay'),
  ('east-coast-summer-escape', 7, 'Departure', 'Drive back via Ella or Kandy to the airport.', null),

  ('kandy-and-tea-country-short-break', 1, 'Colombo to Kandy', 'Drive to Kandy, visiting the Temple of the Tooth in the evening.', 'Kandy'),
  ('kandy-and-tea-country-short-break', 2, 'Kandy to Nuwara Eliya', 'The Peradeniya gardens, then waterfalls and a tea factory on the way up.', 'Nuwara Eliya'),
  ('kandy-and-tea-country-short-break', 3, 'Return', 'A morning walk around Gregory Lake, then the drive back.', null),

  ('galle-day-trip-from-colombo', 1, 'Galle and the south coast', 'Expressway to Galle, a walk around the fort, stilt fishermen near Koggala and a beach stop on the way back.', null),
  ('sigiriya-and-dambulla-day-trip', 1, 'Sigiriya and Dambulla', 'An early start, the Sigiriya climb, the Dambulla cave temples and the drive back.', null),
  ('colombo-city-tour', 1, 'Colombo', 'Gangaramaya Temple, Pettah market, the Fort district, Independence Square and Galle Face Green.', null),
  ('kandy-to-ella-train-with-luggage-transfer', 1, 'Kandy to Ella by train', 'Station drop-off, the train journey, and pickup with your luggage at Ella.', 'Ella')
) as x(tour_slug, day, title, descr, overnight)
join public.tours t on t.slug = x.tour_slug
on conflict do nothing;
